import type { Concept } from '../types'

export const algebra: Concept[] = [
  // ── Algebra ──────────────────────────────────────────────────────────────
  {
    id: 'variables-expressions',
    title: 'Variables & Expressions',
    short: 'Variables',
    domain: 'algebra',
    level: 1,
    prerequisites: ['arithmetic-operations'],
    summary: 'A letter is a box that can hold any number.',
    estMinutes: 15,
    tags: ['unknown', 'expression', 'substitution'],
  },
  {
    id: 'linear-equations',
    title: 'Equations as a Balance',
    short: 'Linear Equations',
    domain: 'algebra',
    level: 2,
    prerequisites: ['variables-expressions'],
    summary: 'Keep the scale level: whatever you do to one side, do to the other.',
    estMinutes: 25,
    tags: ['solve for x', 'linear equation', 'balance'],
  },
  {
    id: 'inequalities',
    title: 'Inequalities',
    domain: 'algebra',
    level: 2,
    prerequisites: ['linear-equations'],
    summary: 'Not one answer but a whole range of them.',
    estMinutes: 15,
    tags: ['less than', 'greater than', 'interval'],
  },
  {
    id: 'coordinate-plane',
    title: 'The Coordinate Plane',
    short: 'Coordinates',
    domain: 'algebra',
    level: 1,
    prerequisites: ['number-line'],
    summary: 'Two number lines at right angles give every point an address.',
    estMinutes: 15,
    tags: ['x axis', 'y axis', 'cartesian', 'plotting points'],
  },
  {
    id: 'slope-linear-functions',
    title: 'Slope & Lines',
    domain: 'algebra',
    level: 2,
    prerequisites: ['linear-equations', 'coordinate-plane', 'ratios-proportions'],
    summary: 'Steepness as a number: rise over run, and the equation y = mx + b.',
    estMinutes: 25,
    tags: ['gradient', 'y = mx + b', 'intercept', 'linear function', 'rate of change'],
  },
  {
    id: 'systems-of-equations',
    title: 'Systems of Equations',
    short: 'Systems',
    domain: 'algebra',
    level: 2,
    prerequisites: ['slope-linear-functions'],
    summary: 'Two conditions at once: where two lines cross.',
    estMinutes: 20,
    tags: ['simultaneous equations', 'intersection', 'elimination', 'substitution'],
  },
  {
    id: 'polynomials',
    title: 'Polynomials',
    domain: 'algebra',
    level: 2,
    prerequisites: ['variables-expressions', 'exponents'],
    summary: 'Sums of powers: the building blocks of smooth curves.',
    estMinutes: 20,
    tags: ['degree', 'expanding', 'terms', 'coefficients'],
  },
  {
    id: 'factoring',
    title: 'Factoring',
    domain: 'algebra',
    level: 2,
    prerequisites: ['polynomials', 'primes-factorization'],
    summary: 'Turn a sum into a product to find where things equal zero.',
    estMinutes: 20,
    tags: ['factorise', 'common factor', 'difference of squares'],
  },
  {
    id: 'quadratics',
    title: 'Quadratics & Parabolas',
    short: 'Quadratics',
    domain: 'algebra',
    level: 3,
    prerequisites: ['factoring', 'functions-intro', 'roots-radicals'],
    summary: 'The shape of a thrown ball, and the formula that finds its roots.',
    estMinutes: 30,
    tags: ['parabola', 'quadratic formula', 'vertex', 'discriminant', 'completing the square'],
  },
  {
    id: 'complex-numbers',
    title: 'Complex Numbers',
    domain: 'algebra',
    level: 3,
    prerequisites: ['quadratics'],
    summary: 'A second dimension for numbers, where multiplying means rotating.',
    estMinutes: 25,
    tags: ['imaginary', 'i', 'complex plane', 'argand'],
  },

  // ── Functions ────────────────────────────────────────────────────────────
  {
    id: 'functions-intro',
    title: 'What Is a Function?',
    short: 'Functions',
    domain: 'functions',
    level: 2,
    prerequisites: ['variables-expressions', 'coordinate-plane'],
    summary: 'A machine that turns each input into exactly one output.',
    estMinutes: 15,
    tags: ['input', 'output', 'domain', 'range', 'graph'],
  },
  {
    id: 'function-transformations',
    title: 'Shift, Stretch & Flip',
    short: 'Transformations',
    domain: 'functions',
    level: 2,
    prerequisites: ['functions-intro', 'slope-linear-functions'],
    summary: 'Move and reshape any graph with four knobs.',
    estMinutes: 25,
    tags: ['translation', 'dilation', 'reflection', 'graph transformations'],
  },
  {
    id: 'composition-inverses',
    title: 'Composition & Inverses',
    short: 'Composition',
    domain: 'functions',
    level: 3,
    prerequisites: ['functions-intro'],
    summary: 'Chain functions together, and run them backwards.',
    estMinutes: 20,
    tags: ['inverse function', 'f of g', 'one-to-one'],
  },
  {
    id: 'exponential-growth',
    title: 'Exponential Growth & Decay',
    short: 'Exponentials',
    domain: 'functions',
    level: 2,
    prerequisites: ['functions-intro', 'exponents', 'decimals-percentages'],
    summary: 'Growth that feeds on itself: interest, viruses and radioactive decay.',
    estMinutes: 25,
    tags: ['compound interest', 'e', 'half-life', 'doubling'],
  },
  {
    id: 'logarithms',
    title: 'Logarithms',
    domain: 'functions',
    level: 3,
    prerequisites: ['exponential-growth', 'composition-inverses'],
    summary: 'How many times must I multiply? Logs turn multiplication into addition.',
    estMinutes: 25,
    tags: ['log', 'ln', 'log scale', 'decibels', 'slide rule'],
  },
  {
    id: 'sequences',
    title: 'Sequences & Patterns',
    short: 'Sequences',
    domain: 'functions',
    level: 2,
    prerequisites: ['functions-intro', 'exponents'],
    summary: 'Ordered lists of numbers that follow a rule.',
    estMinutes: 15,
    tags: ['arithmetic sequence', 'geometric sequence', 'fibonacci', 'recursion'],
  },
  {
    id: 'polynomial-rational-functions',
    title: 'Polynomial & Rational Functions',
    short: 'Rational Functions',
    domain: 'functions',
    level: 3,
    prerequisites: ['quadratics', 'function-transformations'],
    summary: 'Bumps, roots and asymptotes: reading the shape of a formula.',
    estMinutes: 20,
    tags: ['asymptote', 'end behaviour', 'cubic'],
  },
]
