import type { Concept } from '../types'

export const applied: Concept[] = [
  {
    id: 'gradient-descent',
    title: 'Gradient Descent',
    domain: 'applied',
    level: 4,
    prerequisites: ['gradient', 'optimization'],
    summary: 'Learn by rolling downhill: how machines minimize their error.',
    estMinutes: 30,
    tags: ['learning rate', 'loss function', 'training', 'optimization', 'machine learning'],
  },
  {
    id: 'pca',
    title: 'Principal Component Analysis',
    short: 'PCA',
    domain: 'applied',
    level: 5,
    prerequisites: ['eigenvectors', 'correlation'],
    summary: 'Find the directions where data varies most, and compress it.',
    estMinutes: 30,
    tags: ['dimensionality reduction', 'principal components', 'covariance matrix'],
  },
  {
    id: 'logistic-regression',
    title: 'Logistic Regression',
    short: 'Logistic Reg.',
    domain: 'applied',
    level: 4,
    prerequisites: [
      'linear-regression',
      'logarithms',
      'gradient-descent',
      'conditional-probability',
    ],
    summary: 'Squash a line into a probability to classify yes versus no.',
    estMinutes: 25,
    tags: ['sigmoid', 'classification', 'log loss', 'cross-entropy'],
  },
  {
    id: 'neural-networks',
    title: 'Neural Networks & Backpropagation',
    short: 'Neural Networks',
    domain: 'applied',
    level: 5,
    prerequisites: ['chain-rule', 'matrix-multiplication', 'logistic-regression'],
    summary: 'Layers of tiny functions, trained with the chain rule.',
    estMinutes: 30,
    tags: ['deep learning', 'backprop', 'neuron', 'activation'],
  },
  {
    id: 'markov-chains',
    title: 'Markov Chains',
    domain: 'applied',
    level: 4,
    prerequisites: ['conditional-probability', 'matrix-multiplication'],
    summary: 'Random walks between states, and where they settle in the long run.',
    estMinutes: 25,
    tags: ['transition matrix', 'stationary distribution', 'pagerank', 'random walk'],
  },
  {
    id: 'entropy-information',
    title: 'Entropy & Information',
    short: 'Entropy',
    domain: 'applied',
    level: 4,
    prerequisites: ['logarithms', 'random-variables'],
    summary: 'Measure surprise in bits: the math behind compression and ML losses.',
    estMinutes: 20,
    tags: ['information theory', 'bits', 'cross-entropy', 'shannon'],
  },
  {
    id: 'fourier-series',
    title: 'Fourier Series',
    short: 'Fourier',
    domain: 'applied',
    level: 4,
    prerequisites: ['trig-graphs', 'integrals'],
    summary: 'Build any wave from circles spinning at different speeds.',
    estMinutes: 25,
    tags: ['fourier', 'frequency', 'epicycles', 'signal processing', 'square wave'],
  },
  {
    id: 'rsa-cryptography',
    title: 'Public-Key Cryptography (RSA)',
    short: 'RSA',
    domain: 'applied',
    level: 4,
    prerequisites: ['modular-arithmetic', 'exponents'],
    summary: "Primes and clock arithmetic that keep the internet's secrets.",
    estMinutes: 25,
    tags: ['encryption', 'public key', 'rsa', 'primes'],
  },
]
