import type { Concept } from '../types'

export const calculus: Concept[] = [
  // ── Calculus ─────────────────────────────────────────────────────────────
  {
    id: 'limits',
    title: 'Limits',
    domain: 'calculus',
    level: 3,
    prerequisites: ['sequences'],
    summary: 'What a function approaches as you zoom in closer and closer.',
    estMinutes: 20,
    tags: ['limit', 'approach', 'epsilon delta'],
  },
  {
    id: 'continuity',
    title: 'Continuity',
    domain: 'calculus',
    level: 3,
    prerequisites: ['limits'],
    summary: 'Graphs you can draw without lifting your pen.',
    estMinutes: 15,
    tags: ['continuous', 'jump', 'hole', 'asymptote'],
  },
  {
    id: 'derivatives',
    title: 'The Derivative',
    short: 'Derivative',
    domain: 'calculus',
    level: 3,
    prerequisites: ['limits', 'slope-linear-functions'],
    summary: 'Zoom into a curve until it looks straight: its slope is the derivative.',
    estMinutes: 25,
    tags: ['tangent', 'rate of change', 'differentiation', 'slope'],
  },
  {
    id: 'derivative-rules',
    title: 'Derivative Rules',
    domain: 'calculus',
    level: 3,
    prerequisites: ['derivatives', 'polynomials'],
    summary: 'Shortcuts for powers, sums and products.',
    estMinutes: 20,
    tags: ['power rule', 'product rule', 'quotient rule'],
  },
  {
    id: 'chain-rule',
    title: 'The Chain Rule',
    short: 'Chain Rule',
    domain: 'calculus',
    level: 4,
    prerequisites: ['derivative-rules', 'composition-inverses'],
    summary: 'Rates multiply when functions are chained together.',
    estMinutes: 20,
    tags: ['composite', 'backpropagation'],
  },
  {
    id: 'optimization',
    title: 'Optimization',
    domain: 'calculus',
    level: 4,
    prerequisites: ['derivative-rules'],
    summary: 'Find the best: maxima and minima sit where the slope is zero.',
    estMinutes: 20,
    tags: ['maximum', 'minimum', 'critical point', 'extrema'],
  },
  {
    id: 'newtons-method',
    title: "Newton's Method",
    domain: 'calculus',
    level: 4,
    prerequisites: ['derivatives'],
    summary: 'Ride tangent lines to find roots in a few fast steps.',
    estMinutes: 15,
    tags: ['root finding', 'iteration', 'numerical methods'],
  },
  {
    id: 'integrals',
    title: 'The Integral',
    short: 'Integral',
    domain: 'calculus',
    level: 3,
    prerequisites: ['limits', 'area-perimeter'],
    summary: 'Add up infinitely many thin slices to measure area.',
    estMinutes: 25,
    tags: ['riemann sum', 'area under curve', 'integration'],
  },
  {
    id: 'fundamental-theorem',
    title: 'Fundamental Theorem of Calculus',
    short: 'Fundamental Theorem',
    domain: 'calculus',
    level: 4,
    prerequisites: ['derivatives', 'integrals'],
    summary: 'Area and slope are inverse operations.',
    estMinutes: 25,
    tags: ['ftc', 'antiderivative', 'accumulation'],
  },
  {
    id: 'integration-techniques',
    title: 'Integration Techniques',
    short: 'Integration Tricks',
    domain: 'calculus',
    level: 4,
    prerequisites: ['fundamental-theorem', 'chain-rule'],
    summary: 'Substitution and integration by parts: derivative rules run backwards.',
    estMinutes: 25,
    tags: ['u-substitution', 'integration by parts'],
  },
  {
    id: 'infinite-series',
    title: 'Infinite Series',
    short: 'Series',
    domain: 'calculus',
    level: 4,
    prerequisites: ['limits'],
    summary: 'Adding forever can give a finite answer, or blow up.',
    estMinutes: 20,
    tags: ['convergence', 'geometric series', 'harmonic series', 'zeno'],
  },
  {
    id: 'taylor-series',
    title: 'Taylor Series',
    short: 'Taylor Series',
    domain: 'calculus',
    level: 4,
    prerequisites: ['infinite-series', 'derivative-rules'],
    summary: 'Approximate any smooth function with a polynomial.',
    estMinutes: 25,
    tags: ['maclaurin', 'approximation', 'power series'],
  },

  // ── Multivariable calculus ───────────────────────────────────────────────
  {
    id: 'multivariable-functions',
    title: 'Surfaces & Contour Maps',
    short: 'Surfaces',
    domain: 'multivariable',
    level: 4,
    prerequisites: ['functions-intro'],
    summary: 'Functions of two inputs as landscapes and topographic maps.',
    estMinutes: 20,
    tags: ['contour', 'level curves', 'heatmap', '3d graph'],
  },
  {
    id: 'partial-derivatives',
    title: 'Partial Derivatives',
    short: 'Partials',
    domain: 'multivariable',
    level: 4,
    prerequisites: ['derivatives', 'multivariable-functions'],
    summary: 'The slope as you walk in one direction at a time.',
    estMinutes: 20,
    tags: ['partial', 'slice'],
  },
  {
    id: 'gradient',
    title: 'The Gradient',
    short: 'Gradient',
    domain: 'multivariable',
    level: 4,
    prerequisites: ['partial-derivatives', 'vectors'],
    summary: 'An arrow pointing straight uphill.',
    estMinutes: 20,
    tags: ['steepest ascent', 'nabla', 'directional derivative'],
  },
  {
    id: 'double-integrals',
    title: 'Double Integrals',
    domain: 'multivariable',
    level: 5,
    prerequisites: ['integrals', 'multivariable-functions'],
    summary: 'Volume under a surface, by stacking slices.',
    estMinutes: 20,
    tags: ['volume', 'iterated integral'],
  },
  {
    id: 'vector-fields',
    title: 'Vector Fields',
    domain: 'multivariable',
    level: 4,
    prerequisites: ['vectors', 'multivariable-functions'],
    summary: 'An arrow at every point: wind, currents and forces.',
    estMinutes: 20,
    tags: ['flow', 'field lines', 'divergence', 'curl'],
  },
  {
    id: 'lagrange-multipliers',
    title: 'Constrained Optimization',
    short: 'Lagrange',
    domain: 'multivariable',
    level: 5,
    prerequisites: ['gradient', 'optimization'],
    summary: 'Find the best point on a path: where contour lines just touch it.',
    estMinutes: 25,
    tags: ['lagrange multipliers', 'constraint'],
  },

  // ── Differential equations ───────────────────────────────────────────────
  {
    id: 'intro-differential-equations',
    title: 'What Is a Differential Equation?',
    short: 'Differential Eqs',
    domain: 'differential-equations',
    level: 4,
    prerequisites: ['derivatives', 'exponential-growth'],
    summary: 'Equations about rates of change: describe the motion, find the path.',
    estMinutes: 20,
    tags: ['ode', 'rate equation', 'initial value'],
  },
  {
    id: 'slope-fields-euler',
    title: "Slope Fields & Euler's Method",
    short: 'Slope Fields',
    domain: 'differential-equations',
    level: 4,
    prerequisites: ['intro-differential-equations'],
    summary: 'Follow the arrows step by step to predict the future.',
    estMinutes: 20,
    tags: ['direction field', 'euler method', 'numerical solution'],
  },
  {
    id: 'population-models',
    title: 'Population Models',
    short: 'Population',
    domain: 'differential-equations',
    level: 4,
    prerequisites: ['slope-fields-euler'],
    summary: 'Exponential versus logistic growth: what happens when resources run out.',
    estMinutes: 20,
    tags: ['logistic', 'carrying capacity', 'epidemic'],
  },
  {
    id: 'oscillations',
    title: 'Springs & Oscillations',
    short: 'Oscillations',
    domain: 'differential-equations',
    level: 4,
    prerequisites: ['intro-differential-equations', 'trig-graphs'],
    summary: 'Why springs, pendulums and circuits all sing the same sine wave.',
    estMinutes: 25,
    tags: ['harmonic oscillator', 'damping', 'resonance'],
  },
  {
    id: 'phase-portraits',
    title: 'Phase Portraits',
    domain: 'differential-equations',
    level: 5,
    prerequisites: ['oscillations', 'vector-fields', 'eigenvectors'],
    summary: 'Predator and prey: watch whole systems evolve as flows.',
    estMinutes: 25,
    tags: ['lotka volterra', 'stability', 'equilibrium', 'systems'],
  },
]
