import type { Concept } from '../types'

export const foundations: Concept[] = [
  // ── Numbers ──────────────────────────────────────────────────────────────
  {
    id: 'number-line',
    title: 'Number Line & Integers',
    short: 'Number Line',
    domain: 'numbers',
    level: 1,
    prerequisites: [],
    summary: 'Every number has a place. Negative numbers live to the left of zero.',
    estMinutes: 15,
    tags: ['integers', 'negative numbers', 'zero', 'absolute value'],
  },
  {
    id: 'arithmetic-operations',
    title: 'Operations as Movement',
    short: 'Operations',
    domain: 'numbers',
    level: 1,
    prerequisites: ['number-line'],
    summary: 'Adding is a step, multiplying is a stretch: arithmetic as motion on a line.',
    estMinutes: 15,
    tags: ['addition', 'subtraction', 'multiplication', 'division', 'order of operations'],
  },
  {
    id: 'fractions',
    title: 'Fractions',
    domain: 'numbers',
    level: 1,
    prerequisites: ['arithmetic-operations'],
    summary: 'A fraction is a number made by cutting a whole into equal parts.',
    estMinutes: 20,
    tags: ['numerator', 'denominator', 'equivalent fractions'],
  },
  {
    id: 'decimals-percentages',
    title: 'Decimals & Percentages',
    short: 'Decimals & %',
    domain: 'numbers',
    level: 1,
    prerequisites: ['fractions'],
    summary: 'Two more ways to write fractions, and why % is everywhere.',
    estMinutes: 15,
    tags: ['percent', 'decimal', 'discount', 'interest'],
  },
  {
    id: 'ratios-proportions',
    title: 'Ratios & Proportions',
    short: 'Ratios',
    domain: 'numbers',
    level: 1,
    prerequisites: ['fractions'],
    summary: 'Compare quantities by scaling: recipes, maps and exchange rates.',
    estMinutes: 15,
    tags: ['ratio', 'proportion', 'rate', 'scale'],
  },
  {
    id: 'exponents',
    title: 'Exponents & Powers',
    short: 'Exponents',
    domain: 'numbers',
    level: 1,
    prerequisites: ['arithmetic-operations'],
    summary: 'Repeated multiplication, and how fast it explodes.',
    estMinutes: 15,
    tags: ['powers', 'squares', 'cubes', 'scientific notation'],
  },
  {
    id: 'roots-radicals',
    title: 'Roots & Radicals',
    short: 'Roots',
    domain: 'numbers',
    level: 2,
    prerequisites: ['exponents'],
    summary: 'Undo a power: which number squared gives 2?',
    estMinutes: 15,
    tags: ['square root', 'cube root', 'radical'],
  },
  {
    id: 'primes-factorization',
    title: 'Primes & Factorization',
    short: 'Primes',
    domain: 'numbers',
    level: 1,
    prerequisites: ['arithmetic-operations'],
    summary: 'Primes are the atoms of multiplication: every whole number is built from them.',
    estMinutes: 15,
    tags: ['prime numbers', 'factors', 'gcd', 'lcm', 'sieve'],
  },
  {
    id: 'real-numbers',
    title: 'Rational & Irrational Numbers',
    short: 'Real Numbers',
    domain: 'numbers',
    level: 2,
    prerequisites: ['roots-radicals', 'decimals-percentages'],
    summary: 'Some numbers can never be written as a fraction, like √2 and π.',
    estMinutes: 15,
    tags: ['irrational', 'rational', 'real line'],
  },

  // ── Discrete math ────────────────────────────────────────────────────────
  {
    id: 'sets-venn',
    title: 'Sets & Venn Diagrams',
    short: 'Sets',
    domain: 'discrete',
    level: 1,
    prerequisites: [],
    summary: 'Group things, overlap the groups, and count what is inside.',
    estMinutes: 15,
    tags: ['union', 'intersection', 'complement', 'venn'],
  },
  {
    id: 'logic-truth-tables',
    title: 'Logic & Truth Tables',
    short: 'Logic',
    domain: 'discrete',
    level: 1,
    prerequisites: [],
    summary: 'AND, OR, NOT: the rules behind every computer and every proof.',
    estMinutes: 15,
    tags: ['boolean', 'and', 'or', 'not', 'implication'],
  },
  {
    id: 'counting',
    title: 'The Counting Principle',
    short: 'Counting',
    domain: 'discrete',
    level: 1,
    prerequisites: ['arithmetic-operations'],
    summary: 'Choices multiply: 3 shirts and 4 trousers make 12 outfits.',
    estMinutes: 15,
    tags: ['multiplication principle', 'tree diagram'],
  },
  {
    id: 'permutations-combinations',
    title: 'Permutations & Combinations',
    short: 'Perms & Combos',
    domain: 'discrete',
    level: 2,
    prerequisites: ['counting', 'fractions'],
    summary: 'Count arrangements and selections without listing them all.',
    estMinutes: 20,
    tags: ['factorial', 'n choose k', 'binomial coefficient'],
  },
  {
    id: 'induction',
    title: 'Proof by Induction',
    short: 'Induction',
    domain: 'discrete',
    level: 3,
    prerequisites: ['logic-truth-tables', 'sequences'],
    summary: 'Knock over the first domino, show each one tips the next, and they all fall.',
    estMinutes: 20,
    tags: ['proof', 'dominoes', 'recursion'],
  },
  {
    id: 'modular-arithmetic',
    title: 'Modular Arithmetic',
    short: 'Modular',
    domain: 'discrete',
    level: 2,
    prerequisites: ['primes-factorization'],
    summary: 'Clock arithmetic: numbers that wrap around.',
    estMinutes: 15,
    tags: ['mod', 'remainder', 'clock'],
  },
  {
    id: 'number-bases',
    title: 'Binary & Number Bases',
    short: 'Binary',
    domain: 'discrete',
    level: 2,
    prerequisites: ['exponents'],
    summary: 'Why computers count in 0s and 1s.',
    estMinutes: 15,
    tags: ['binary', 'hexadecimal', 'base 2', 'place value'],
  },
  {
    id: 'graphs-networks',
    title: 'Graphs & Networks',
    short: 'Graphs',
    domain: 'discrete',
    level: 2,
    prerequisites: ['sets-venn'],
    summary: 'Dots and lines that model friendships, roads and the internet.',
    estMinutes: 20,
    tags: ['graph theory', 'nodes', 'edges', 'shortest path'],
  },
]
