import type { Concept } from '../types'

export const geometry: Concept[] = [
  // ── Geometry ─────────────────────────────────────────────────────────────
  {
    id: 'angles',
    title: 'Angles',
    domain: 'geometry',
    level: 1,
    prerequisites: ['arithmetic-operations'],
    summary: 'Measuring turns, from a quarter turn to a full revolution.',
    estMinutes: 15,
    tags: ['degrees', 'right angle', 'acute', 'obtuse'],
  },
  {
    id: 'area-perimeter',
    title: 'Area & Perimeter',
    domain: 'geometry',
    level: 1,
    prerequisites: ['arithmetic-operations'],
    summary: 'How much fence versus how much field.',
    estMinutes: 15,
    tags: ['rectangle', 'square units', 'perimeter'],
  },
  {
    id: 'triangles',
    title: 'Triangles',
    domain: 'geometry',
    level: 1,
    prerequisites: ['angles'],
    summary: 'The simplest polygon, and why its angles always add to 180°.',
    estMinutes: 15,
    tags: ['angle sum', 'isosceles', 'equilateral'],
  },
  {
    id: 'circles-pi',
    title: 'Circles & π',
    domain: 'geometry',
    level: 2,
    prerequisites: ['area-perimeter', 'ratios-proportions'],
    summary: 'Unroll a circle and π appears: the ratio that never ends.',
    estMinutes: 20,
    tags: ['pi', 'circumference', 'radius', 'diameter'],
  },
  {
    id: 'pythagorean-theorem',
    title: 'Pythagorean Theorem',
    short: 'Pythagoras',
    domain: 'geometry',
    level: 2,
    prerequisites: ['triangles', 'area-perimeter', 'roots-radicals'],
    summary: 'a² + b² = c²: squares on the sides of a right triangle.',
    estMinutes: 20,
    tags: ['hypotenuse', 'right triangle', 'pythagoras'],
  },
  {
    id: 'similarity',
    title: 'Similarity & Scaling',
    short: 'Similarity',
    domain: 'geometry',
    level: 2,
    prerequisites: ['triangles', 'ratios-proportions'],
    summary: 'Same shape, different size: how lengths, areas and volumes scale.',
    estMinutes: 15,
    tags: ['similar triangles', 'scale factor'],
  },
  {
    id: 'distance-midpoint',
    title: 'Distance & Midpoint',
    short: 'Distance',
    domain: 'geometry',
    level: 2,
    prerequisites: ['pythagorean-theorem', 'coordinate-plane'],
    summary: 'Pythagoras in coordinates: how far apart are two points?',
    estMinutes: 15,
    tags: ['distance formula', 'midpoint formula'],
  },
  {
    id: 'geometric-transformations',
    title: 'Rigid Transformations',
    short: 'Rigid Motions',
    domain: 'geometry',
    level: 2,
    prerequisites: ['coordinate-plane', 'angles'],
    summary: 'Slide, turn and flip shapes without changing them.',
    estMinutes: 20,
    tags: ['translation', 'rotation', 'reflection', 'symmetry'],
  },
  {
    id: 'volume-surface-area',
    title: 'Volume & Surface Area',
    short: 'Volume',
    domain: 'geometry',
    level: 2,
    prerequisites: ['circles-pi'],
    summary: 'How much a solid holds versus how much wrapping it needs.',
    estMinutes: 20,
    tags: ['cylinder', 'cube', 'sphere', 'prism'],
  },

  // ── Trigonometry ─────────────────────────────────────────────────────────
  {
    id: 'right-triangle-trig',
    title: 'Sine, Cosine & Tangent',
    short: 'Sin, Cos, Tan',
    domain: 'trigonometry',
    level: 2,
    prerequisites: ['similarity', 'pythagorean-theorem'],
    summary: "Ratios of a right triangle's sides that depend only on its angle.",
    estMinutes: 25,
    tags: ['soh cah toa', 'sine', 'cosine', 'tangent'],
  },
  {
    id: 'radians',
    title: 'Radians',
    domain: 'trigonometry',
    level: 2,
    prerequisites: ['circles-pi', 'angles'],
    summary: 'Measure angles by arc length: the natural unit of rotation.',
    estMinutes: 15,
    tags: ['radian', 'arc length', 'degrees to radians'],
  },
  {
    id: 'unit-circle',
    title: 'The Unit Circle',
    short: 'Unit Circle',
    domain: 'trigonometry',
    level: 3,
    prerequisites: ['right-triangle-trig', 'radians', 'coordinate-plane'],
    summary: 'Sine and cosine for every angle, as the shadows of a point going round.',
    estMinutes: 25,
    tags: ['unit circle', 'special angles', 'quadrants'],
  },
  {
    id: 'trig-graphs',
    title: 'Waves: Sine & Cosine Graphs',
    short: 'Waves',
    domain: 'trigonometry',
    level: 3,
    prerequisites: ['unit-circle', 'function-transformations'],
    summary: 'Unroll the circle into a wave, then tune amplitude, frequency and phase.',
    estMinutes: 25,
    tags: ['sine wave', 'amplitude', 'frequency', 'period', 'phase', 'sound'],
  },
  {
    id: 'trig-identities',
    title: 'Trig Identities',
    short: 'Identities',
    domain: 'trigonometry',
    level: 3,
    prerequisites: ['unit-circle'],
    summary: 'Equations that hold for every angle, all visible on the unit circle.',
    estMinutes: 20,
    tags: ['pythagorean identity', 'double angle', 'sum formulas'],
  },
  {
    id: 'law-of-sines-cosines',
    title: 'Laws of Sines & Cosines',
    short: 'Sine & Cosine Laws',
    domain: 'trigonometry',
    level: 3,
    prerequisites: ['right-triangle-trig'],
    summary: 'Solve any triangle, not just right-angled ones.',
    estMinutes: 20,
    tags: ['law of sines', 'law of cosines', 'triangulation'],
  },
  {
    id: 'polar-coordinates',
    title: 'Polar Coordinates',
    short: 'Polar',
    domain: 'trigonometry',
    level: 3,
    prerequisites: ['unit-circle'],
    summary: 'Locate points by distance and angle; draw roses and spirals.',
    estMinutes: 20,
    tags: ['polar', 'rose curve', 'spiral'],
  },
  {
    id: 'eulers-formula',
    title: "Euler's Formula",
    domain: 'trigonometry',
    level: 4,
    prerequisites: ['complex-numbers', 'unit-circle', 'exponential-growth'],
    summary: 'e^{iθ} = cos θ + i sin θ: exponentials that rotate.',
    estMinutes: 25,
    tags: ['euler', 'complex exponential', 'e to the i pi'],
  },
]
