import type { Concept } from '../types'

export const linearAlgebra: Concept[] = [
  {
    id: 'vectors',
    title: 'Vectors',
    domain: 'linear-algebra',
    level: 2,
    prerequisites: ['coordinate-plane', 'pythagorean-theorem'],
    summary: 'Arrows with length and direction: add them tip to tail.',
    estMinutes: 25,
    tags: ['vector addition', 'magnitude', 'scalar multiplication', 'components'],
  },
  {
    id: 'linear-combinations-span',
    title: 'Linear Combinations & Span',
    short: 'Span',
    domain: 'linear-algebra',
    level: 3,
    prerequisites: ['vectors'],
    summary: 'Scale and add arrows: which points can you reach?',
    estMinutes: 25,
    tags: ['span', 'linear independence', 'basis'],
  },
  {
    id: 'dot-product',
    title: 'Dot Product & Projection',
    short: 'Dot Product',
    domain: 'linear-algebra',
    level: 3,
    prerequisites: ['vectors', 'right-triangle-trig'],
    summary: 'How much one arrow points along another: the shadow test.',
    estMinutes: 25,
    tags: ['projection', 'cosine similarity', 'orthogonal', 'angle between vectors'],
  },
  {
    id: 'linear-transformations',
    title: 'Matrices as Transformations',
    short: 'Matrices',
    domain: 'linear-algebra',
    level: 3,
    prerequisites: ['linear-combinations-span', 'functions-intro'],
    summary: 'A matrix moves the whole plane: its columns say where the axes land.',
    estMinutes: 30,
    tags: ['matrix', 'linear map', 'basis vectors', 'i hat', 'j hat'],
  },
  {
    id: 'matrix-multiplication',
    title: 'Matrix Multiplication',
    short: 'Matrix Product',
    domain: 'linear-algebra',
    level: 3,
    prerequisites: ['linear-transformations', 'composition-inverses'],
    summary: 'Do one transformation, then another: that is multiplication.',
    estMinutes: 25,
    tags: ['matrix product', 'composition', 'non-commutative'],
  },
  {
    id: 'determinant',
    title: 'The Determinant',
    short: 'Determinant',
    domain: 'linear-algebra',
    level: 3,
    prerequisites: ['linear-transformations'],
    summary: 'How much a transformation stretches area, and whether it flips space.',
    estMinutes: 25,
    tags: ['det', 'area scaling', 'orientation', 'singular'],
  },
  {
    id: 'inverse-matrix',
    title: 'Inverses & Linear Systems',
    short: 'Inverse Matrix',
    domain: 'linear-algebra',
    level: 4,
    prerequisites: ['determinant', 'matrix-multiplication', 'systems-of-equations'],
    summary: 'Undo a transformation to solve many equations at once.',
    estMinutes: 30,
    tags: ['inverse', 'Ax = b', 'gaussian elimination', 'singular matrix'],
  },
  {
    id: 'eigenvectors',
    title: 'Eigenvectors & Eigenvalues',
    short: 'Eigenvectors',
    domain: 'linear-algebra',
    level: 4,
    prerequisites: ['determinant', 'quadratics'],
    summary: 'The special directions a transformation only stretches.',
    estMinutes: 30,
    tags: ['eigenvalue', 'characteristic polynomial', 'power iteration', 'pagerank'],
  },
  {
    id: 'change-of-basis',
    title: 'Change of Basis',
    domain: 'linear-algebra',
    level: 4,
    prerequisites: ['inverse-matrix'],
    summary: "Describe the same arrow in someone else's coordinates.",
    estMinutes: 25,
    tags: ['basis', 'coordinates', 'similar matrices'],
  },
  {
    id: 'least-squares',
    title: 'Orthogonality & Least Squares',
    short: 'Least Squares',
    domain: 'linear-algebra',
    level: 4,
    prerequisites: ['dot-product', 'inverse-matrix'],
    summary: "The closest you can get when there's no exact solution.",
    estMinutes: 25,
    tags: ['orthogonal projection', 'normal equations', 'best fit'],
  },
  {
    id: 'svd',
    title: 'Singular Value Decomposition',
    short: 'SVD',
    domain: 'linear-algebra',
    level: 5,
    prerequisites: ['eigenvectors', 'least-squares'],
    summary: 'Every matrix is a rotation, a stretch, and another rotation.',
    estMinutes: 30,
    tags: ['singular values', 'low rank', 'image compression'],
  },
]
