import type { Concept } from '../types'

export const probability: Concept[] = [
  // ── Probability ──────────────────────────────────────────────────────────
  {
    id: 'probability-basics',
    title: 'What Is Probability?',
    short: 'Probability',
    domain: 'probability',
    level: 2,
    prerequisites: ['fractions', 'sets-venn'],
    summary: 'Chance as a long-run frequency: flip, roll and watch it settle.',
    estMinutes: 25,
    tags: ['chance', 'coin', 'dice', 'sample space', 'event'],
  },
  {
    id: 'conditional-probability',
    title: 'Conditional Probability',
    short: 'Conditional',
    domain: 'probability',
    level: 3,
    prerequisites: ['probability-basics'],
    summary: 'How chances change once you know something.',
    estMinutes: 25,
    tags: ['given', 'independence', 'monty hall', 'tree diagram'],
  },
  {
    id: 'bayes-theorem',
    title: "Bayes' Theorem",
    short: 'Bayes',
    domain: 'probability',
    level: 3,
    prerequisites: ['conditional-probability'],
    summary: 'Update beliefs with evidence, and see why most positive tests can be false.',
    estMinutes: 25,
    tags: ['bayes', 'prior', 'posterior', 'base rate', 'false positive'],
  },
  {
    id: 'random-variables',
    title: 'Random Variables & Expected Value',
    short: 'Expected Value',
    domain: 'probability',
    level: 3,
    prerequisites: ['probability-basics', 'functions-intro'],
    summary: 'Numbers that come from chance, and their long-run average.',
    estMinutes: 20,
    tags: ['expectation', 'mean', 'distribution'],
  },
  {
    id: 'binomial-distribution',
    title: 'The Binomial Distribution',
    short: 'Binomial',
    domain: 'probability',
    level: 3,
    prerequisites: ['random-variables', 'permutations-combinations'],
    summary: 'Count successes in repeated trials: the Galton board.',
    estMinutes: 25,
    tags: ['galton board', 'bernoulli', 'successes'],
  },
  {
    id: 'law-of-large-numbers',
    title: 'Law of Large Numbers',
    short: 'Large Numbers',
    domain: 'probability',
    level: 3,
    prerequisites: ['random-variables'],
    summary: 'Averages settle down as you collect more data.',
    estMinutes: 15,
    tags: ['lln', 'convergence', 'running average'],
  },
  {
    id: 'continuous-distributions',
    title: 'Continuous Distributions',
    short: 'Continuous',
    domain: 'probability',
    level: 4,
    prerequisites: ['random-variables', 'integrals'],
    summary: 'When outcomes form a continuum, probability becomes area.',
    estMinutes: 20,
    tags: ['pdf', 'density', 'uniform', 'exponential distribution'],
  },
  {
    id: 'normal-distribution',
    title: 'The Normal Distribution',
    short: 'Normal',
    domain: 'probability',
    level: 3,
    prerequisites: ['binomial-distribution', 'variance-std'],
    summary: 'The bell curve: why so many things cluster around an average.',
    estMinutes: 25,
    tags: ['bell curve', 'gaussian', 'z-score', '68-95-99.7'],
  },
  {
    id: 'central-limit-theorem',
    title: 'Central Limit Theorem',
    short: 'Central Limit',
    domain: 'probability',
    level: 4,
    prerequisites: ['normal-distribution', 'law-of-large-numbers'],
    summary: 'Average almost anything and you get a bell curve.',
    estMinutes: 25,
    tags: ['clt', 'sample mean', 'sampling'],
  },

  // ── Statistics ───────────────────────────────────────────────────────────
  {
    id: 'describing-data',
    title: 'Mean, Median & Mode',
    short: 'Mean & Median',
    domain: 'statistics',
    level: 1,
    prerequisites: ['fractions'],
    summary: 'Three ways to find the centre of a pile of numbers.',
    estMinutes: 20,
    tags: ['average', 'mean', 'median', 'mode', 'outlier'],
  },
  {
    id: 'variance-std',
    title: 'Variance & Standard Deviation',
    short: 'Variance',
    domain: 'statistics',
    level: 2,
    prerequisites: ['describing-data', 'roots-radicals'],
    summary: 'How spread out the data is, measured with squares.',
    estMinutes: 25,
    tags: ['spread', 'standard deviation', 'sigma', 'deviation'],
  },
  {
    id: 'correlation',
    title: 'Covariance & Correlation',
    short: 'Correlation',
    domain: 'statistics',
    level: 3,
    prerequisites: ['variance-std', 'coordinate-plane'],
    summary: 'Do two things rise and fall together?',
    estMinutes: 20,
    tags: ['covariance', 'pearson r', 'scatter plot', 'causation'],
  },
  {
    id: 'linear-regression',
    title: 'Linear Regression',
    short: 'Regression',
    domain: 'statistics',
    level: 3,
    prerequisites: ['correlation', 'slope-linear-functions'],
    summary: 'Draw the line that best fits a cloud of points.',
    estMinutes: 30,
    tags: ['least squares', 'line of best fit', 'residuals', 'prediction'],
  },
  {
    id: 'sampling-distributions',
    title: 'Sampling Distributions',
    short: 'Sampling',
    domain: 'statistics',
    level: 4,
    prerequisites: ['central-limit-theorem'],
    summary: 'How much would the answer change with a different sample?',
    estMinutes: 20,
    tags: ['standard error', 'sample', 'population'],
  },
  {
    id: 'confidence-intervals',
    title: 'Confidence Intervals',
    domain: 'statistics',
    level: 4,
    prerequisites: ['sampling-distributions'],
    summary: 'A range that catches the truth 95% of the time.',
    estMinutes: 20,
    tags: ['margin of error', '95%', 'estimate'],
  },
  {
    id: 'hypothesis-testing',
    title: 'Hypothesis Testing',
    domain: 'statistics',
    level: 4,
    prerequisites: ['confidence-intervals', 'conditional-probability'],
    summary: 'Could this result be a fluke? p-values explained by simulation.',
    estMinutes: 25,
    tags: ['p-value', 'null hypothesis', 'significance', 'a/b test'],
  },
  {
    id: 'maximum-likelihood',
    title: 'Maximum Likelihood',
    domain: 'statistics',
    level: 4,
    prerequisites: ['random-variables', 'logarithms', 'optimization'],
    summary: 'Pick the parameters that make your data least surprising.',
    estMinutes: 20,
    tags: ['mle', 'likelihood', 'estimation', 'log-likelihood'],
  },
]
